package com.example.ui.screens

data class Language(val name: String, val tag: String)

val languages = listOf(
    Language("English", "en"),
    Language("Afrikaans", "af"),
    Language("Albanian / Shqip", "sq"),
    Language("Amharic / አማርኛ", "am"),
    Language("Arabic / العربية", "ar"),
    Language("Armenian / Հայերեն", "hy"),
    Language("Azerbaijani / Azərbaycan dili", "az"),
    Language("Basque / Euskara", "eu"),
    Language("Belarusian / Беларуская", "be"),
    Language("Bengali / বাংলা", "bn"),
    Language("Bosnian / Bosanski", "bs"),
    Language("Bulgarian / Български", "bg"),
    Language("Burmese / မြန်မာဘာသာ", "my"),
    Language("Catalan / Català", "ca"),
    Language("Chinese (Simplified) / 简体中文", "zh-CN"),
    Language("Chinese (Traditional) / 繁體中文", "zh-TW"),
    Language("Corsican / Corsu", "co"),
    Language("Croatian / Hrvatski", "hr"),
    Language("Czech / Čeština", "cs"),
    Language("Danish / Dansk", "da"),
    Language("Dutch / Nederlands", "nl"),
    Language("Estonian / Eesti", "et"),
    Language("Filipino / Tagalog", "tl"),
    Language("Finnish / Suomi", "fi"),
    Language("French / Français", "fr"),
    Language("Frisian / Frysk", "fy"),
    Language("Galician / Galego", "gl"),
    Language("Georgian / ქართული", "ka"),
    Language("German / Deutsch", "de"),
    Language("Greek / Ελληνικά", "el"),
    Language("Gujarati / ગુજરાતી", "gu"),
    Language("Haitian Creole / Kreyòl Ayisyen", "ht"),
    Language("Hausa / هَوُسَ", "ha"),
    Language("Hawaiian / ʻŌlelo Hawaiʻi", "haw"),
    Language("Hebrew / עברית", "he"),
    Language("Hindi / हिन्दी", "hi"),
    Language("Hungarian / Magyar", "hu"),
    Language("Icelandic / Íslenska", "is"),
    Language("Igbo / Igbo", "ig"),
    Language("Indonesian / Bahasa Indonesia", "id"),
    Language("Inuktitut / ᐃᓄᒃᑎᑐᑦ", "iu"),
    Language("Irish / Gaeilge", "ga"),
    Language("Italian / Italiano", "it"),
    Language("Japanese / 日本語", "ja"),
    Language("Javanese / Basa Jawa", "jv"),
    Language("Kannada / ಕನ್ನಡ", "kn"),
    Language("Khmer / ភាសាខ្មែរ", "km"),
    Language("Korean / 한국어", "ko"),
    Language("Kazakh / Қазақша", "kk"),
    Language("Kurdish / Kurdî", "ku"),
    Language("Kyrgyz / Кыргызча", "ky"),
    Language("Lao / ລາວ", "lo"),
    Language("Latvian / Latviešu", "lv"),
    Language("Lithuanian / Lietuvių", "lt"),
    Language("Macedonian / Македонски", "mk"),
    Language("Malagasy / Malagasy", "mg"),
    Language("Malay / Bahasa Melayu", "ms"),
    Language("Malayalam / മലയാളം", "ml"),
    Language("Maltese / Malti", "mt"),
    Language("Maori / Māori", "mi"),
    Language("Marathi / मराठी", "mr"),
    Language("Mongolian / Монгол", "mn"),
    Language("Nepali / नेपाली", "ne"),
    Language("Norwegian / Norsk", "nb"),
    Language("Odia / ଓଡ଼ିଆ", "or"),
    Language("Pashto / پښتو", "ps"),
    Language("Persian / فارسی", "fa"),
    Language("Polish / Polski", "pl"),
    Language("Portuguese (Brazil) / Português (Brasil)", "pt-BR"),
    Language("Portuguese (Portugal) / Português (Portugal)", "pt-PT"),
    Language("Punjabi / ਪੰਜਾਬੀ", "pa"),
    Language("Romanian / Română", "ro"),
    Language("Russian / Русский", "ru"),
    Language("Samoan / Gagana Samoa", "sm"),
    Language("Sanskrit / संस्कृतम्", "sa"),
    Language("Serbian / Српски", "sr"),
    Language("Sesotho / Sesotho", "st"),
    Language("Sindhi / سنڌي", "sd"),
    Language("Shona / chiShona", "sn"),
    Language("Sinhala / සිංහල", "si"),
    Language("Slovak / Slovenčina", "sk"),
    Language("Slovenian / Slovenščina", "sl"),
    Language("Somali / Soomaali", "so"),
    Language("Spanish / Español", "es"),
    Language("Swahili / Kiswahili", "sw"),
    Language("Swedish / Svenska", "sv"),
    Language("Tagalog / Tagalog", "tl"),
    Language("Tajik / Тоҷикӣ", "tg"),
    Language("Tamil / தமிழ்", "ta"),
    Language("Tatar / Татарча", "tt"),
    Language("Telugu / తెలుగు", "te"),
    Language("Thai / ไทย", "th"),
    Language("Tibetan / བོད་སྐད", "bo"),
    Language("Tigrinya / ትግርኛ", "ti"),
    Language("Turkmen / Türkmençe", "tk"),
    Language("Turkish / Türkçe", "tr"),
    Language("Ukrainian / Українська", "uk"),
    Language("Urdu / اردو", "ur"),
    Language("Uyghur / ئۇيغۇرچە", "ug"),
    Language("Uzbek / Oʻzbekcha", "uz"),
    Language("Vietnamese / Tiếng Việt", "vi"),
    Language("Welsh / Cymraeg", "cy"),
    Language("Xhosa / isiXhosa", "xh"),
    Language("Yiddish / ייִדיש", "yi"),
    Language("Yoruba / Yorùbá", "yo"),
    Language("Zulu / isiZulu", "zu"),
)

fun languageDisplayName(tag: String): String {
    val index = languages.indexOfFirst { it.tag == tag }
    return if (index >= 0) languages[index].name else "English"
}
